apiVersion: batch/v1
kind: Job
metadata:
  name: audit-tool
  namespace: kasten-io
spec:
  template:
    spec:
      serviceAccount: k10-k10
      serviceAccountName: k10-k10
      containers:
      - name: audit-tool
        image: michaelcourcy/audit-tool:0.0.13-amd64
        command: ["/audit"]
        env: 
        - name: KASTEN_NAMESPACE 
          value: kasten-io
        - name: KASTEN_RELEASE
          value: k10
      restartPolicy: Never
  backoffLimit: 4
